name: Peter Lab
markdown: kramdown
highlighter: rouge

timezone: Asia/Shanghai
siteurl: http://www.peter-lab.com/
assets: http://dn-peterlab.qbox.me/assets/
uploads: http://dn-peterlab.qbox.me/uploads/

permalink: /:title

kramdown:
  input: GFM
  syntax_highlighter: rouge