name: Peter Lab
markdown: kramdown
highlighter: rouge

timezone: Asia/Shanghai
siteurl: https://www.0x1b.cn
assets: /assets/
uploads: /assets/uploads/

permalink: /:title

kramdown:
  input: GFM
  syntax_highlighter: rouge
